#SETTINGS for prior net & toy data_set

# DATASET
N_CLASSES = 3
SAMPLES_PER_CLASS = 10000
SAMPLES_OOD = 10000
NOISE = 0.3
# PREPROCESS
ID_LOGIT = 100
OOD_LOGIT = 1
TRAIN_RATIO = 0.7
#MODEL
N_LAYERS = 5
N_NEURONS = 64
ACTIVATION = 'relu'
#TRAINING
BATCH_SIZE = 100
N_EPOCHS = 20
#PLOT
PLOT_SIMPLEX = True
